
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.kelola_data_sopir;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class RegistrasiSopir extends javax.swing.JFrame {

    // Hapus constructor yang menerima parent frame.
    // Controller yang akan mengatur navigasi.
    public RegistrasiSopir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    // Getters untuk Input
    public String getNama() { return NAMA_TEXT_FIELD.getText(); }
    public String getNoTelepon() { return NO_TELEPON_TEXT_FIELD.getText(); }
    public String getUsername() { return USERNAME_TEXT_FIELD.getText(); }
    public String getPassword() { return PASSWORD_TEXT_FIELD.getText(); }
    public String getArmada() { return (String) PILIH_ARMADA_COMBO_BOX.getSelectedItem(); }

    // Listener Simpan
    public void addSimpanListener(ActionListener listener) {
        REGISTER_BUTTON.addActionListener(listener);
    }

    // Listener Back
    public void addMenuListener(ActionListener listener) {
        MENU_BUTTON.addActionListener(listener);
    }
    
    // Method Helper untuk pesan
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_PANEL = new javax.swing.JPanel();
        MENU_BUTTON = new javax.swing.JButton();
        REGISTRASI_SOPIR_PANEL = new javax.swing.JPanel();
        REGISTRASI_SOPIR_TEXT_PANEL = new javax.swing.JPanel();
        REGISTRASI_SOPIR_TEXT = new javax.swing.JLabel();
        NO_TELEPON_PANEL = new javax.swing.JPanel();
        NO_TELEPON_TEXT = new javax.swing.JLabel();
        NO_TELEPON_TEXT_FIELD = new javax.swing.JTextField();
        NAMA_PANEL = new javax.swing.JPanel();
        NAMA_TEXT = new javax.swing.JLabel();
        NAMA_TEXT_FIELD = new javax.swing.JTextField();
        USERNAME_PANEL = new javax.swing.JPanel();
        USERNAME_TEXT = new javax.swing.JLabel();
        USERNAME_TEXT_FIELD = new javax.swing.JTextField();
        PASSWORD_PANEL = new javax.swing.JPanel();
        PASSWORD_TEXT = new javax.swing.JLabel();
        PASSWORD_TEXT_FIELD = new javax.swing.JTextField();
        ARMADA_PANEL = new javax.swing.JPanel();
        ARMADA_TEXT = new javax.swing.JLabel();
        PILIH_ARMADA_COMBO_BOX = new javax.swing.JComboBox<>();
        REGISTER_BUTTON = new javax.swing.JButton();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        MAIN_PANEL.setPreferredSize(new java.awt.Dimension(960, 540));

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        REGISTRASI_SOPIR_PANEL.setBackground(new java.awt.Color(220, 238, 235));

        REGISTRASI_SOPIR_TEXT_PANEL.setBackground(new java.awt.Color(55, 119, 142));

        REGISTRASI_SOPIR_TEXT.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        REGISTRASI_SOPIR_TEXT.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRASI_SOPIR_TEXT.setText("Registrasi Sopir");

        javax.swing.GroupLayout REGISTRASI_SOPIR_TEXT_PANELLayout = new javax.swing.GroupLayout(REGISTRASI_SOPIR_TEXT_PANEL);
        REGISTRASI_SOPIR_TEXT_PANEL.setLayout(REGISTRASI_SOPIR_TEXT_PANELLayout);
        REGISTRASI_SOPIR_TEXT_PANELLayout.setHorizontalGroup(
            REGISTRASI_SOPIR_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRASI_SOPIR_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REGISTRASI_SOPIR_TEXT)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        REGISTRASI_SOPIR_TEXT_PANELLayout.setVerticalGroup(
            REGISTRASI_SOPIR_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRASI_SOPIR_TEXT_PANELLayout.createSequentialGroup()
                .addComponent(REGISTRASI_SOPIR_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        NO_TELEPON_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NO_TELEPON_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NO_TELEPON_TEXT.setText("No Telepon :");

        javax.swing.GroupLayout NO_TELEPON_PANELLayout = new javax.swing.GroupLayout(NO_TELEPON_PANEL);
        NO_TELEPON_PANEL.setLayout(NO_TELEPON_PANELLayout);
        NO_TELEPON_PANELLayout.setHorizontalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NO_TELEPON_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NO_TELEPON_TEXT_FIELD)
                .addContainerGap())
        );
        NO_TELEPON_PANELLayout.setVerticalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NO_TELEPON_TEXT)
                    .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NAMA_TEXT.setBackground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NAMA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setText("Nama :");

        javax.swing.GroupLayout NAMA_PANELLayout = new javax.swing.GroupLayout(NAMA_PANEL);
        NAMA_PANEL.setLayout(NAMA_PANELLayout);
        NAMA_PANELLayout.setHorizontalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMA_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NAMA_TEXT_FIELD)
                .addContainerGap())
        );
        NAMA_PANELLayout.setVerticalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        USERNAME_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        USERNAME_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        USERNAME_TEXT.setText("Username :");

        javax.swing.GroupLayout USERNAME_PANELLayout = new javax.swing.GroupLayout(USERNAME_PANEL);
        USERNAME_PANEL.setLayout(USERNAME_PANELLayout);
        USERNAME_PANELLayout.setHorizontalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USERNAME_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        USERNAME_PANELLayout.setVerticalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, USERNAME_PANELLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_TEXT)
                    .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PASSWORD_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PASSWORD_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        PASSWORD_TEXT.setText("Password :");

        javax.swing.GroupLayout PASSWORD_PANELLayout = new javax.swing.GroupLayout(PASSWORD_PANEL);
        PASSWORD_PANEL.setLayout(PASSWORD_PANELLayout);
        PASSWORD_PANELLayout.setHorizontalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PASSWORD_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PASSWORD_PANELLayout.setVerticalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PASSWORD_PANELLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD_TEXT)
                    .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ARMADA_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ARMADA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        ARMADA_TEXT.setText("Armada :");

        PILIH_ARMADA_COMBO_BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DPS-01", "DPS-02" }));
        PILIH_ARMADA_COMBO_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIH_ARMADA_COMBO_BOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARMADA_PANELLayout = new javax.swing.GroupLayout(ARMADA_PANEL);
        ARMADA_PANEL.setLayout(ARMADA_PANELLayout);
        ARMADA_PANELLayout.setHorizontalGroup(
            ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ARMADA_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(PILIH_ARMADA_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ARMADA_PANELLayout.setVerticalGroup(
            ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ARMADA_TEXT)
                    .addComponent(PILIH_ARMADA_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        REGISTER_BUTTON.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        REGISTER_BUTTON.setForeground(new java.awt.Color(65, 82, 154));
        REGISTER_BUTTON.setText("Registrasi");
        REGISTER_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTER_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout REGISTRASI_SOPIR_PANELLayout = new javax.swing.GroupLayout(REGISTRASI_SOPIR_PANEL);
        REGISTRASI_SOPIR_PANEL.setLayout(REGISTRASI_SOPIR_PANELLayout);
        REGISTRASI_SOPIR_PANELLayout.setHorizontalGroup(
            REGISTRASI_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRASI_SOPIR_PANELLayout.createSequentialGroup()
                .addComponent(REGISTRASI_SOPIR_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(REGISTRASI_SOPIR_PANELLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(REGISTRASI_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REGISTER_BUTTON)
                    .addGroup(REGISTRASI_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NAMA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(USERNAME_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PASSWORD_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ARMADA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        REGISTRASI_SOPIR_PANELLayout.setVerticalGroup(
            REGISTRASI_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRASI_SOPIR_PANELLayout.createSequentialGroup()
                .addComponent(REGISTRASI_SOPIR_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NAMA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USERNAME_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PASSWORD_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ARMADA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(REGISTER_BUTTON)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, 19, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, Short.MAX_VALUE)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, Short.MAX_VALUE)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(REGISTRASI_SOPIR_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REGISTRASI_SOPIR_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
  
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    private void REGISTER_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTER_BUTTONActionPerformed
       
    }//GEN-LAST:event_REGISTER_BUTTONActionPerformed

    private void PILIH_ARMADA_COMBO_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIH_ARMADA_COMBO_BOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PILIH_ARMADA_COMBO_BOXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ARMADA_PANEL;
    private javax.swing.JLabel ARMADA_TEXT;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JPanel NAMA_PANEL;
    private javax.swing.JLabel NAMA_TEXT;
    private javax.swing.JTextField NAMA_TEXT_FIELD;
    private javax.swing.JPanel NO_TELEPON_PANEL;
    private javax.swing.JLabel NO_TELEPON_TEXT;
    private javax.swing.JTextField NO_TELEPON_TEXT_FIELD;
    private javax.swing.JPanel PASSWORD_PANEL;
    private javax.swing.JLabel PASSWORD_TEXT;
    private javax.swing.JTextField PASSWORD_TEXT_FIELD;
    private javax.swing.JComboBox<String> PILIH_ARMADA_COMBO_BOX;
    private javax.swing.JButton REGISTER_BUTTON;
    private javax.swing.JPanel REGISTRASI_SOPIR_PANEL;
    private javax.swing.JLabel REGISTRASI_SOPIR_TEXT;
    private javax.swing.JPanel REGISTRASI_SOPIR_TEXT_PANEL;
    private javax.swing.JPanel USERNAME_PANEL;
    private javax.swing.JLabel USERNAME_TEXT;
    private javax.swing.JTextField USERNAME_TEXT_FIELD;
    // End of variables declaration//GEN-END:variables
}
