/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.kelola_data_pelanggan;


/**
 *
 * @author Aditya
 */
public class DashboardMenu extends javax.swing.JFrame {

    public DashboardMenu() {
        initComponents();
        this.MENU_BUTTON1.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INFO_PENJUALAN_DIALOG = new javax.swing.JDialog();
        PANEL_TURUNAN_INFO_PENJUALAN = new javax.swing.JPanel();
        CETAK_LAPORAN_BUTTON = new javax.swing.JButton();
        UPDATE_STATUS_PEMBAYARAN_BUTTON = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        MAIN_PANEL = new javax.swing.JPanel();
        PANEL_MENU = new javax.swing.JPanel();
        MENU_BUTTON = new javax.swing.JButton();
        ATUR_JADWAL_KIRIMAN_BUTTON = new javax.swing.JButton();
        INFO_PENJUALAN_BUTTON = new javax.swing.JButton();
        KELOLA_DATA_GALON_BUTTON = new javax.swing.JButton();
        KELOLA_DATA_PELANGGAN_TBUTTON = new javax.swing.JToggleButton();
        KELOLA_DATA_SOPIR_TBUTTON = new javax.swing.JToggleButton();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        HYMAP_TEXT = new javax.swing.JLabel();
        MENU_BUTTON1 = new javax.swing.JButton();

        INFO_PENJUALAN_DIALOG.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        INFO_PENJUALAN_DIALOG.setTitle("Info Penjualan");
        INFO_PENJUALAN_DIALOG.setSize(new java.awt.Dimension(300, 300));
        INFO_PENJUALAN_DIALOG.setType(java.awt.Window.Type.UTILITY);

        PANEL_TURUNAN_INFO_PENJUALAN.setBackground(new java.awt.Color(255, 255, 255));

        CETAK_LAPORAN_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Cetak Laporan.png"))); // NOI18N
        CETAK_LAPORAN_BUTTON.setBorder(null);
        CETAK_LAPORAN_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CETAK_LAPORAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETAK_LAPORAN_BUTTONActionPerformed(evt);
            }
        });

        UPDATE_STATUS_PEMBAYARAN_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Update Status Pembayaran.png"))); // NOI18N
        UPDATE_STATUS_PEMBAYARAN_BUTTON.setBorder(null);
        UPDATE_STATUS_PEMBAYARAN_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE_STATUS_PEMBAYARAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_STATUS_PEMBAYARAN_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_TURUNAN_INFO_PENJUALANLayout = new javax.swing.GroupLayout(PANEL_TURUNAN_INFO_PENJUALAN);
        PANEL_TURUNAN_INFO_PENJUALAN.setLayout(PANEL_TURUNAN_INFO_PENJUALANLayout);
        PANEL_TURUNAN_INFO_PENJUALANLayout.setHorizontalGroup(
            PANEL_TURUNAN_INFO_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_TURUNAN_INFO_PENJUALANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_TURUNAN_INFO_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CETAK_LAPORAN_BUTTON)
                    .addComponent(UPDATE_STATUS_PEMBAYARAN_BUTTON))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PANEL_TURUNAN_INFO_PENJUALANLayout.setVerticalGroup(
            PANEL_TURUNAN_INFO_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_TURUNAN_INFO_PENJUALANLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CETAK_LAPORAN_BUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UPDATE_STATUS_PEMBAYARAN_BUTTON)
                .addGap(0, 122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout INFO_PENJUALAN_DIALOGLayout = new javax.swing.GroupLayout(INFO_PENJUALAN_DIALOG.getContentPane());
        INFO_PENJUALAN_DIALOG.getContentPane().setLayout(INFO_PENJUALAN_DIALOGLayout);
        INFO_PENJUALAN_DIALOGLayout.setHorizontalGroup(
            INFO_PENJUALAN_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(INFO_PENJUALAN_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PANEL_TURUNAN_INFO_PENJUALAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        INFO_PENJUALAN_DIALOGLayout.setVerticalGroup(
            INFO_PENJUALAN_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
            .addGroup(INFO_PENJUALAN_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PANEL_TURUNAN_INFO_PENJUALAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        MAIN_PANEL.setMaximumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setMinimumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setPreferredSize(new java.awt.Dimension(960, 540));

        PANEL_MENU.setBackground(new java.awt.Color(255, 255, 255));

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.setBorder(null);
        MENU_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MENU_BUTTON.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        ATUR_JADWAL_KIRIMAN_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Atur Jadwal Kiriman.png"))); // NOI18N
        ATUR_JADWAL_KIRIMAN_BUTTON.setBorder(null);
        ATUR_JADWAL_KIRIMAN_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ATUR_JADWAL_KIRIMAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATUR_JADWAL_KIRIMAN_BUTTONActionPerformed(evt);
            }
        });

        INFO_PENJUALAN_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Info Penjualan.png"))); // NOI18N
        INFO_PENJUALAN_BUTTON.setBorder(null);
        INFO_PENJUALAN_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INFO_PENJUALAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFO_PENJUALAN_BUTTONActionPerformed(evt);
            }
        });

        KELOLA_DATA_GALON_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Set Harga Default.png"))); // NOI18N
        KELOLA_DATA_GALON_BUTTON.setBorder(null);
        KELOLA_DATA_GALON_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KELOLA_DATA_GALON_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELOLA_DATA_GALON_BUTTONActionPerformed(evt);
            }
        });

        KELOLA_DATA_PELANGGAN_TBUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Kelola Data Pelanggan (241 x 50 piksel).png"))); // NOI18N
        KELOLA_DATA_PELANGGAN_TBUTTON.setBorder(null);
        KELOLA_DATA_PELANGGAN_TBUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KELOLA_DATA_PELANGGAN_TBUTTON.setMargin(new java.awt.Insets(2, 2, 2, 2));
        KELOLA_DATA_PELANGGAN_TBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELOLA_DATA_PELANGGAN_TBUTTONActionPerformed(evt);
            }
        });

        KELOLA_DATA_SOPIR_TBUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Button/Kelola Data Sopir.png"))); // NOI18N
        KELOLA_DATA_SOPIR_TBUTTON.setBorder(null);
        KELOLA_DATA_SOPIR_TBUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KELOLA_DATA_SOPIR_TBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELOLA_DATA_SOPIR_TBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_MENULayout = new javax.swing.GroupLayout(PANEL_MENU);
        PANEL_MENU.setLayout(PANEL_MENULayout);
        PANEL_MENULayout.setHorizontalGroup(
            PANEL_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_MENULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KELOLA_DATA_PELANGGAN_TBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ATUR_JADWAL_KIRIMAN_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KELOLA_DATA_GALON_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PANEL_MENULayout.createSequentialGroup()
                        .addComponent(INFO_PENJUALAN_BUTTON)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_MENULayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KELOLA_DATA_SOPIR_TBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PANEL_MENULayout.setVerticalGroup(
            PANEL_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_MENULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KELOLA_DATA_PELANGGAN_TBUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KELOLA_DATA_SOPIR_TBUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ATUR_JADWAL_KIRIMAN_BUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INFO_PENJUALAN_BUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KELOLA_DATA_GALON_BUTTON)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HYMAP_TEXT.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        HYMAP_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        HYMAP_TEXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HYMAP_TEXT.setText("H Y M A P");
        HYMAP_TEXT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MENU_BUTTON1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON1.setBorder(null);
        MENU_BUTTON1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MENU_BUTTON1.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(PANEL_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MENU_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MAIN_PANELLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(HYMAP_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(293, 293, 293)))
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANEL_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MENU_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MAIN_PANELLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(HYMAP_TEXT)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INFO_PENJUALAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFO_PENJUALAN_BUTTONActionPerformed
        INFO_PENJUALAN_DIALOG.setVisible(true);
    }//GEN-LAST:event_INFO_PENJUALAN_BUTTONActionPerformed

    private void ATUR_JADWAL_KIRIMAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATUR_JADWAL_KIRIMAN_BUTTONActionPerformed
        Admin.AturJadwalPengiriman.PilihArmada run = new Admin.AturJadwalPengiriman.PilihArmada();
        run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ATUR_JADWAL_KIRIMAN_BUTTONActionPerformed

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
        
        MENU_BUTTON1.setVisible(true);     
        PANEL_MENU.setVisible(false);  
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    private void KELOLA_DATA_PELANGGAN_TBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELOLA_DATA_PELANGGAN_TBUTTONActionPerformed
        Admin.KelolaDataPelanggan.DataPelanggan kelolaDataPelanggan = new Admin.KelolaDataPelanggan.DataPelanggan();
        kelolaDataPelanggan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KELOLA_DATA_PELANGGAN_TBUTTONActionPerformed

    private void KELOLA_DATA_SOPIR_TBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELOLA_DATA_SOPIR_TBUTTONActionPerformed
        Admin.KelolaDataSopir.DataSopir kelolaDataSopir = new Admin.KelolaDataSopir.DataSopir();
        kelolaDataSopir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KELOLA_DATA_SOPIR_TBUTTONActionPerformed

    private void CETAK_LAPORAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETAK_LAPORAN_BUTTONActionPerformed
        Admin.InfoPenjualan.CetakLaporan run = new Admin.InfoPenjualan.CetakLaporan();
        run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CETAK_LAPORAN_BUTTONActionPerformed

    private void UPDATE_STATUS_PEMBAYARAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_STATUS_PEMBAYARAN_BUTTONActionPerformed
        Admin.InfoPenjualan.UpdateStatusPembayaran run = new Admin.InfoPenjualan.UpdateStatusPembayaran();
        run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UPDATE_STATUS_PEMBAYARAN_BUTTONActionPerformed

    private void MENU_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTON1ActionPerformed
        PANEL_MENU.setVisible(true);     
        MENU_BUTTON1.setVisible(false);  
    }//GEN-LAST:event_MENU_BUTTON1ActionPerformed

    private void KELOLA_DATA_GALON_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELOLA_DATA_GALON_BUTTONActionPerformed

    }//GEN-LAST:event_KELOLA_DATA_GALON_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATUR_JADWAL_KIRIMAN_BUTTON;
    private javax.swing.JButton CETAK_LAPORAN_BUTTON;
    private javax.swing.JLabel HYMAP_TEXT;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JButton INFO_PENJUALAN_BUTTON;
    private javax.swing.JDialog INFO_PENJUALAN_DIALOG;
    private javax.swing.JButton KELOLA_DATA_GALON_BUTTON;
    private javax.swing.JToggleButton KELOLA_DATA_PELANGGAN_TBUTTON;
    private javax.swing.JToggleButton KELOLA_DATA_SOPIR_TBUTTON;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JButton MENU_BUTTON1;
    private javax.swing.JPanel PANEL_MENU;
    private javax.swing.JPanel PANEL_TURUNAN_INFO_PENJUALAN;
    private javax.swing.JButton UPDATE_STATUS_PEMBAYARAN_BUTTON;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
