/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.kelola_data_pelanggan;


//Database
import com.mycompany.admin.view.DashboardMenu;
import com.mycompany.admin.config.DatabaseConnection;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Aditya
 */
public class TambahDataPelanggan extends javax.swing.JFrame {

    public TambahDataPelanggan() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Jangan ada logika lain di constructor
    }

    // --- GETTER DATA (Agar Controller bisa membaca input) ---
    public String getNamaInput() {
        return NAMA_TEXT_FIELD.getText();
    }

    public String getAlamatInput() {
        return ALAMAT_TEXT_FIELD.getText();
    }

    public String getNoTeleponInput() {
        return NO_TELEPON_TEXT_FIELD.getText();
    }

    public String getDaerahInput() {
        return (String) DAERAH_KIRIMAN_COMBO_BOX.getSelectedItem();
    }

    // --- LISTENER (Agar Controller bisa memasang aksi) ---
    public void addSimpanListener(ActionListener listener) {
        jButton1.addActionListener(listener);
    }

    public void addKembaliListener(ActionListener listener) {
        jButton2.addActionListener(listener);
    }
    
    // --- HELPER UNTUK PESAN ---
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void showWarning(String message) {
        JOptionPane.showMessageDialog(this, message, "Peringatan", JOptionPane.WARNING_MESSAGE);
    }

    public void clearForm() {
        NAMA_TEXT_FIELD.setText("");
        ALAMAT_TEXT_FIELD.setText("");
        NO_TELEPON_TEXT_FIELD.setText("");
        DAERAH_KIRIMAN_COMBO_BOX.setSelectedIndex(0);
    }
    // --- BAGIAN GENERATED CODE TETAP SAMA ---
    // PENTING: Hapus isi method jButton1ActionPerformed di Source Code Netbeans
    // Biarkan kosong seperti ini:
    // KOSONGKAN INI. Logika dipindah ke Controller via addSimpanListener

    
    /**
     * Creates new form AdminLogin
     */
//    public TambahDataPelanggan(DataPelanggan parent) {
//        initComponents();
//
//        this.parentFrame = parent;
//        this.setLocationRelativeTo(null);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        TAMBAH_DATA_PELANGGAN_PANEL = new javax.swing.JPanel();
        TAMBAH_DATA_PELANGGAN_TEXT_PANEL = new javax.swing.JPanel();
        TAMBAH_DATA_PELANGGAN_TEXT = new javax.swing.JLabel();
        NAMA_PANEL = new javax.swing.JPanel();
        NAMA_TEXT = new javax.swing.JLabel();
        NAMA_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_PANEL = new javax.swing.JPanel();
        ALAMAT_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_TEXT = new javax.swing.JLabel();
        NO_TELEPON_PANEL = new javax.swing.JPanel();
        NO_TELEPON_TEXT = new javax.swing.JLabel();
        NO_TELEPON_TEXT_FIELD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ALAMAT_PANEL1 = new javax.swing.JPanel();
        ALAMAT_TEXT1 = new javax.swing.JLabel();
        DAERAH_KIRIMAN_COMBO_BOX = new javax.swing.JComboBox<>();
        MENU_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        jPanel1.setBackground(new java.awt.Color(172, 210, 202));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 540));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TAMBAH_DATA_PELANGGAN_PANEL.setBackground(new java.awt.Color(205, 228, 223));

        TAMBAH_DATA_PELANGGAN_TEXT_PANEL.setBackground(new java.awt.Color(55, 119, 142));

        TAMBAH_DATA_PELANGGAN_TEXT.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TAMBAH_DATA_PELANGGAN_TEXT.setForeground(new java.awt.Color(255, 255, 255));
        TAMBAH_DATA_PELANGGAN_TEXT.setText("Tambah Data Pelanggan");

        javax.swing.GroupLayout TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout = new javax.swing.GroupLayout(TAMBAH_DATA_PELANGGAN_TEXT_PANEL);
        TAMBAH_DATA_PELANGGAN_TEXT_PANEL.setLayout(TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout);
        TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.setHorizontalGroup(
            TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TAMBAH_DATA_PELANGGAN_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.setVerticalGroup(
            TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAMBAH_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TAMBAH_DATA_PELANGGAN_TEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NAMA_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        NAMA_TEXT.setBackground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setText("Nama:");

        javax.swing.GroupLayout NAMA_PANELLayout = new javax.swing.GroupLayout(NAMA_PANEL);
        NAMA_PANEL.setLayout(NAMA_PANELLayout);
        NAMA_PANELLayout.setHorizontalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMA_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NAMA_PANELLayout.setVerticalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_TEXT)
                    .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ALAMAT_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALAMAT_TEXT_FIELDActionPerformed(evt);
            }
        });

        ALAMAT_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT.setText("Alamat");

        javax.swing.GroupLayout ALAMAT_PANELLayout = new javax.swing.GroupLayout(ALAMAT_PANEL);
        ALAMAT_PANEL.setLayout(ALAMAT_PANELLayout);
        ALAMAT_PANELLayout.setHorizontalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(ALAMAT_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANELLayout.setVerticalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALAMAT_TEXT))
                .addContainerGap())
        );

        NO_TELEPON_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        NO_TELEPON_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NO_TELEPON_TEXT.setText("No Telepon");

        NO_TELEPON_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NO_TELEPON_TEXT_FIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NO_TELEPON_PANELLayout = new javax.swing.GroupLayout(NO_TELEPON_PANEL);
        NO_TELEPON_PANEL.setLayout(NO_TELEPON_PANELLayout);
        NO_TELEPON_PANELLayout.setHorizontalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NO_TELEPON_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NO_TELEPON_PANELLayout.setVerticalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NO_TELEPON_TEXT)
                    .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setForeground(new java.awt.Color(65, 82, 154));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(65, 82, 154));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ALAMAT_PANEL1.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT1.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT1.setText("Daerah kiriman");

        DAERAH_KIRIMAN_COMBO_BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DPS-01", "DPS-02", " " }));
        DAERAH_KIRIMAN_COMBO_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAERAH_KIRIMAN_COMBO_BOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ALAMAT_PANEL1Layout = new javax.swing.GroupLayout(ALAMAT_PANEL1);
        ALAMAT_PANEL1.setLayout(ALAMAT_PANEL1Layout);
        ALAMAT_PANEL1Layout.setHorizontalGroup(
            ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DAERAH_KIRIMAN_COMBO_BOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ALAMAT_PANEL1Layout.setVerticalGroup(
            ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DAERAH_KIRIMAN_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALAMAT_TEXT1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TAMBAH_DATA_PELANGGAN_PANELLayout = new javax.swing.GroupLayout(TAMBAH_DATA_PELANGGAN_PANEL);
        TAMBAH_DATA_PELANGGAN_PANEL.setLayout(TAMBAH_DATA_PELANGGAN_PANELLayout);
        TAMBAH_DATA_PELANGGAN_PANELLayout.setHorizontalGroup(
            TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addComponent(TAMBAH_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ALAMAT_PANEL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NAMA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        TAMBAH_DATA_PELANGGAN_PANELLayout.setVerticalGroup(
            TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TAMBAH_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NAMA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ALAMAT_PANEL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TAMBAH_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(TAMBAH_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(TAMBAH_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
        DashboardMenu dashboard = new DashboardMenu();
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    private void ALAMAT_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALAMAT_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALAMAT_TEXT_FIELDActionPerformed

    private void NO_TELEPON_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NO_TELEPON_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NO_TELEPON_TEXT_FIELDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*DataPelanggan dataPelanggan = new DataPelanggan();
        DefaultTableModel model =(DefaultTableModel) dataPelanggan.getTable().getModel();
        model.addRow(new Object[]{ NAMA_TEXT_FIELD.getText(), 
                                    NO_TELEPON_TEXT_FIELD.getText(), 
                                    ALAMAT_TEXT_FIELD.getText()   
                                  });
        dataPelanggan.setVisible(true);
        this.setVisible(false);*/
        
//        String nama = NAMA_TEXT_FIELD.getText();
//        String alamat = ALAMAT_TEXT_FIELD.getText();
//        String noTelepon = NO_TELEPON_TEXT_FIELD.getText();
//        String daerah = (String) DAERAH_KIRIMAN_COMBO_BOX.getSelectedItem();
//        if (nama.isEmpty() || alamat.isEmpty() || noTelepon.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        String sql = "INSERT INTO pelanggan (nama, alamat, no_telepon, daerah_kiriman) VALUES (?, ?, ?, ?)";
//        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//            pstmt.setString(1, nama);
//            pstmt.setString(2, alamat);
//            pstmt.setString(3, noTelepon);
//            pstmt.setString(4, daerah);
//
//            int affectedRows = pstmt.executeUpdate();
//            if (affectedRows > 0) {
//                JOptionPane.showMessageDialog(this, "Data pelanggan berhasil ditambahkan!");
//                parentFrame.loadTableData; // Refresh tabel di frame utama
//                parentFrame.setVisible(true); // Tampilkan lagi frame utama
//                this.dispose(); // Tutup frame tambah data
//            }
//
//        } catch (SQLException e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Gagal menambahkan data ke database.", "Database Error", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        parentFrame.setVisible(true); // Tampilkan lagi frame utama
//        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DAERAH_KIRIMAN_COMBO_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAERAH_KIRIMAN_COMBO_BOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAERAH_KIRIMAN_COMBO_BOXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALAMAT_PANEL;
    private javax.swing.JPanel ALAMAT_PANEL1;
    private javax.swing.JLabel ALAMAT_TEXT;
    private javax.swing.JLabel ALAMAT_TEXT1;
    private javax.swing.JTextField ALAMAT_TEXT_FIELD;
    private javax.swing.JComboBox<String> DAERAH_KIRIMAN_COMBO_BOX;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JPanel NAMA_PANEL;
    private javax.swing.JLabel NAMA_TEXT;
    private javax.swing.JTextField NAMA_TEXT_FIELD;
    private javax.swing.JPanel NO_TELEPON_PANEL;
    private javax.swing.JLabel NO_TELEPON_TEXT;
    private javax.swing.JTextField NO_TELEPON_TEXT_FIELD;
    private javax.swing.JPanel TAMBAH_DATA_PELANGGAN_PANEL;
    private javax.swing.JLabel TAMBAH_DATA_PELANGGAN_TEXT;
    private javax.swing.JPanel TAMBAH_DATA_PELANGGAN_TEXT_PANEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
