/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sopir.TableAddButton;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author Aditya
 */
public class PanelAction extends javax.swing.JPanel {
    
    public PanelAction() {
        initComponents();
        buttonGroup.add(radioTerkirim);
        buttonGroup.add(radioBelum);
    }
    
    public void initEvent(TableActionEvent event, int row) {
        for (java.awt.event.ActionListener al : radioTerkirim.getActionListeners()) {
            radioTerkirim.removeActionListener(al);
        }
        for (java.awt.event.ActionListener al : radioBelum.getActionListeners()) {
            radioBelum.removeActionListener(al);
        }

        radioTerkirim.addActionListener((ActionEvent e) -> {
            if (radioTerkirim.isSelected()) {
                event.onTerkirim(row);
            }
        });

        radioBelum.addActionListener((ActionEvent e) -> {
            if (radioBelum.isSelected()) {
                event.onBelum(row);
            }
        });
    }
    public void setStatus(String status) {
        if (status != null && status.equalsIgnoreCase("sudah terkirim")) {
            radioTerkirim.setSelected(true);
        } else {
            radioBelum.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        radioTerkirim = new javax.swing.JRadioButton();
        radioBelum = new javax.swing.JRadioButton();

        radioTerkirim.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        radioTerkirim.setText("Terkirim");
        radioTerkirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTerkirimActionPerformed(evt);
            }
        });

        radioBelum.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        radioBelum.setText("Belum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(radioTerkirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBelum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioTerkirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBelum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioTerkirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTerkirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTerkirimActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton radioBelum;
    private javax.swing.JRadioButton radioTerkirim;
    // End of variables declaration//GEN-END:variables
}
