package com.mycompany.hymap_sopir.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aditya
 */
import com.mycompany.hymap_sopir.config.DatabaseConnection;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aditya
 */


public class SopirLogin extends javax.swing.JFrame {
   
    String armada = "NONE";
    
    public SopirLogin() {
        initComponents();
    }
    
    public String getUsernameInput() {
        return USERNAME_TEXT_FIELD.getText();
    }

    public String getPasswordInput() {
        return new String(PASSWORD_TEXT_FIELD.getPassword());
    }

    public void addLoginListener(ActionListener listener) {
        LOGIN_BUTTON.addActionListener(listener);
    }

    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showSuccessMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        BorderU = new javax.swing.JPanel();
        BorderD = new javax.swing.JPanel();
        HYMAP_TEXT = new javax.swing.JLabel();
        LOGIN_BOX = new javax.swing.JPanel();
        PASSWORD_AREA_PANEL = new javax.swing.JPanel();
        PASSWORD_TEXT = new javax.swing.JLabel();
        PASSWORD_TEXT_FIELD = new javax.swing.JPasswordField();
        USERNAME_AREA_PANEL = new javax.swing.JPanel();
        USERNAME_TEXT = new javax.swing.JLabel();
        USERNAME_TEXT_FIELD = new javax.swing.JTextField();
        LOGIN_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(208, 255, 246));

        Background.setBackground(new java.awt.Color(191, 234, 230));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(375, 52));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(375, 26));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        BorderU.setBackground(new java.awt.Color(44, 97, 116));
        BorderU.setMaximumSize(new java.awt.Dimension(375, 52));
        BorderU.setPreferredSize(new java.awt.Dimension(375, 52));

        BorderD.setBackground(new java.awt.Color(46, 86, 103));
        BorderD.setMaximumSize(new java.awt.Dimension(375, 26));
        BorderD.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout BorderDLayout = new javax.swing.GroupLayout(BorderD);
        BorderD.setLayout(BorderDLayout);
        BorderDLayout.setHorizontalGroup(
            BorderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        BorderDLayout.setVerticalGroup(
            BorderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BorderULayout = new javax.swing.GroupLayout(BorderU);
        BorderU.setLayout(BorderULayout);
        BorderULayout.setHorizontalGroup(
            BorderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderULayout.createSequentialGroup()
                .addComponent(BorderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BorderULayout.setVerticalGroup(
            BorderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BorderULayout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(BorderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HYMAP_TEXT.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        HYMAP_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        HYMAP_TEXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HYMAP_TEXT.setText("H Y M A P");

        LOGIN_BOX.setBackground(new java.awt.Color(197, 223, 221));
        LOGIN_BOX.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PASSWORD_AREA_PANEL.setBackground(new java.awt.Color(234, 244, 243));

        PASSWORD_TEXT.setText("Password:");

        javax.swing.GroupLayout PASSWORD_AREA_PANELLayout = new javax.swing.GroupLayout(PASSWORD_AREA_PANEL);
        PASSWORD_AREA_PANEL.setLayout(PASSWORD_AREA_PANELLayout);
        PASSWORD_AREA_PANELLayout.setHorizontalGroup(
            PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_AREA_PANELLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PASSWORD_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PASSWORD_AREA_PANELLayout.setVerticalGroup(
            PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD_TEXT)
                    .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        USERNAME_AREA_PANEL.setBackground(new java.awt.Color(234, 244, 243));

        USERNAME_TEXT.setText("Username:");

        USERNAME_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAME_TEXT_FIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout USERNAME_AREA_PANELLayout = new javax.swing.GroupLayout(USERNAME_AREA_PANEL);
        USERNAME_AREA_PANEL.setLayout(USERNAME_AREA_PANELLayout);
        USERNAME_AREA_PANELLayout.setHorizontalGroup(
            USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_AREA_PANELLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(USERNAME_TEXT)
                .addGap(18, 18, 18)
                .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        USERNAME_AREA_PANELLayout.setVerticalGroup(
            USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_TEXT)
                    .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LOGIN_BUTTON.setBackground(new java.awt.Color(234, 244, 244));
        LOGIN_BUTTON.setText("Login");
        LOGIN_BUTTON.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LOGIN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LOGIN_BOXLayout = new javax.swing.GroupLayout(LOGIN_BOX);
        LOGIN_BOX.setLayout(LOGIN_BOXLayout);
        LOGIN_BOXLayout.setHorizontalGroup(
            LOGIN_BOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGIN_BOXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LOGIN_BOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGIN_BOXLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LOGIN_BOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PASSWORD_AREA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(USERNAME_AREA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LOGIN_BOXLayout.setVerticalGroup(
            LOGIN_BOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGIN_BOXLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(USERNAME_AREA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(PASSWORD_AREA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HYMAP_TEXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeaderD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGIN_BOX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(HYMAP_TEXT)
                .addGap(51, 51, 51)
                .addComponent(LOGIN_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(BorderU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGIN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BUTTONActionPerformed

    }//GEN-LAST:event_LOGIN_BUTTONActionPerformed

    private void USERNAME_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAME_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAME_TEXT_FIELDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BorderD;
    private javax.swing.JPanel BorderU;
    private javax.swing.JLabel HYMAP_TEXT;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel LOGIN_BOX;
    private javax.swing.JButton LOGIN_BUTTON;
    private javax.swing.JPanel PASSWORD_AREA_PANEL;
    private javax.swing.JLabel PASSWORD_TEXT;
    private javax.swing.JPasswordField PASSWORD_TEXT_FIELD;
    private javax.swing.JPanel USERNAME_AREA_PANEL;
    private javax.swing.JLabel USERNAME_TEXT;
    private javax.swing.JTextField USERNAME_TEXT_FIELD;
    // End of variables declaration//GEN-END:variables
}
