/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.login;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditya
 */
public class AdminLogin extends javax.swing.JFrame {
    
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_PANEL = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        HYMAP_TEXT = new javax.swing.JLabel();
        LOGIN_CARD_PANEL = new javax.swing.JPanel();
        LOGIN_PANEL = new javax.swing.JPanel();
        USERNAME_AREA_PANEL = new javax.swing.JPanel();
        USERNAME_TEXT = new javax.swing.JLabel();
        USERNAME_TEXT_FIELD = new javax.swing.JTextField();
        PASSWORD_AREA_PANEL = new javax.swing.JPanel();
        PASSWORD_TEXT = new javax.swing.JLabel();
        PASSWORD_TEXT_FIELD = new javax.swing.JPasswordField();
        LOGIN_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        MAIN_PANEL.setMaximumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setMinimumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setPreferredSize(new java.awt.Dimension(960, 540));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HYMAP_TEXT.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        HYMAP_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        HYMAP_TEXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HYMAP_TEXT.setText("H Y M A P");

        LOGIN_CARD_PANEL.setBackground(new java.awt.Color(205, 228, 223));
        LOGIN_CARD_PANEL.setLayout(new java.awt.CardLayout());

        LOGIN_PANEL.setBackground(new java.awt.Color(197, 223, 218));

        USERNAME_AREA_PANEL.setBackground(new java.awt.Color(234, 244, 243));

        USERNAME_TEXT.setText("Username:");

        USERNAME_TEXT_FIELD.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout USERNAME_AREA_PANELLayout = new javax.swing.GroupLayout(USERNAME_AREA_PANEL);
        USERNAME_AREA_PANEL.setLayout(USERNAME_AREA_PANELLayout);
        USERNAME_AREA_PANELLayout.setHorizontalGroup(
            USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USERNAME_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        USERNAME_AREA_PANELLayout.setVerticalGroup(
            USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(USERNAME_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(USERNAME_AREA_PANELLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(USERNAME_TEXT))
                    .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PASSWORD_AREA_PANEL.setBackground(new java.awt.Color(234, 244, 243));

        PASSWORD_TEXT.setText("Password:");

        javax.swing.GroupLayout PASSWORD_AREA_PANELLayout = new javax.swing.GroupLayout(PASSWORD_AREA_PANEL);
        PASSWORD_AREA_PANEL.setLayout(PASSWORD_AREA_PANELLayout);
        PASSWORD_AREA_PANELLayout.setHorizontalGroup(
            PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PASSWORD_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PASSWORD_AREA_PANELLayout.setVerticalGroup(
            PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_AREA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PASSWORD_AREA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PASSWORD_AREA_PANELLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PASSWORD_TEXT))
                    .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LOGIN_BUTTON.setBackground(new java.awt.Color(234, 244, 244));
        LOGIN_BUTTON.setText("Login");
        LOGIN_BUTTON.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LOGIN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LOGIN_PANELLayout = new javax.swing.GroupLayout(LOGIN_PANEL);
        LOGIN_PANEL.setLayout(LOGIN_PANELLayout);
        LOGIN_PANELLayout.setHorizontalGroup(
            LOGIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGIN_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LOGIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGIN_PANELLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(PASSWORD_AREA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(USERNAME_AREA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LOGIN_PANELLayout.setVerticalGroup(
            LOGIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGIN_PANELLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(USERNAME_AREA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(PASSWORD_AREA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        LOGIN_CARD_PANEL.add(LOGIN_PANEL, "card2");

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HYMAP_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(LOGIN_CARD_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(302, 302, 302))
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(HYMAP_TEXT)
                .addGap(18, 38, Short.MAX_VALUE)
                .addComponent(LOGIN_CARD_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGIN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BUTTONActionPerformed

    }//GEN-LAST:event_LOGIN_BUTTONActionPerformed
    
    public String getUsername() {
        return USERNAME_TEXT_FIELD.getText();
    }

    public String getPassword() {
        // JPasswordField harus diambil sebagai char[] lalu convert string untuk diproses
        return new String(PASSWORD_TEXT_FIELD.getPassword());
    }

    // Method untuk Controller mendengarkan klik tombol
    public void addLoginListener(ActionListener listener) {
        LOGIN_BUTTON.addActionListener(listener);
    }

    // Method untuk menampilkan pesan (agar Controller tidak menyentuh JOptionPane langsung di dalam logic)
    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Login Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showSuccessMessage(String message){
        JOptionPane.showMessageDialog(this, message, "Login Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HYMAP_TEXT;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JButton LOGIN_BUTTON;
    private javax.swing.JPanel LOGIN_CARD_PANEL;
    private javax.swing.JPanel LOGIN_PANEL;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JPanel PASSWORD_AREA_PANEL;
    private javax.swing.JLabel PASSWORD_TEXT;
    private javax.swing.JPasswordField PASSWORD_TEXT_FIELD;
    private javax.swing.JPanel USERNAME_AREA_PANEL;
    private javax.swing.JLabel USERNAME_TEXT;
    private javax.swing.JTextField USERNAME_TEXT_FIELD;
    // End of variables declaration//GEN-END:variables
}
