/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.kelola_data_pelanggan;


//Database
import com.mycompany.admin.view.DashboardMenu;
import com.mycompany.admin.config.DatabaseConnection;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditya
 */

public class EditDataPelanggan extends javax.swing.JFrame {
 
    /**
     * Creates new form AdminLogin
     */
    private int pelangganId;
    
    // Hapus 'DataPelanggan parent' dari constructor. 
    // Controller yang akan mengatur navigasi antar window.
    public EditDataPelanggan(int id, String nama, String alamat, String noTelepon, String daerahPengiriman) {
        initComponents();
        
        this.pelangganId = id;
        
        // Set nilai awal form
        NAMA_TEXT_FIELD.setText(nama);
        ALAMAT_TEXT_FIELD.setText(alamat);
        NO_TELEPON_TEXT_FIELD.setText(noTelepon);
        DAERAH_KIRIMAN_COMBO_BOX.setSelectedItem(daerahPengiriman);

        this.setLocationRelativeTo(null);
    }
    
    // --- GETTER DATA (Untuk Controller) ---
    public int getPelangganId() {
        return pelangganId;
    }

    public String getNamaInput() {
        return NAMA_TEXT_FIELD.getText();
    }
    
    public String getAlamatInput() {
        return ALAMAT_TEXT_FIELD.getText();
    }
    
    public String getNoTeleponInput() {
        return NO_TELEPON_TEXT_FIELD.getText();
    }
    
    public String getDaerahInput() {
        return (String) DAERAH_KIRIMAN_COMBO_BOX.getSelectedItem();
    }

    // --- LISTENER (Hubungan ke Controller) ---
    public void addSimpanListener(ActionListener listener) {
        EDIT_BUTTON.addActionListener(listener);
    }
    
    public void addKembaliListener(ActionListener listener) {
        EDIT_BUTTON1.addActionListener(listener);
    }
    // Listener untuk Tombol Menu (Back to Dashboard)
    public void addMenuListener(ActionListener listener) {
        MENU_BUTTON.addActionListener(listener);
    }
    // --- METODE TAMPILAN DIALOG ---
    // Controller akan memanggil ini, bukan View yang memutuskan kapan muncul
    public void showSuccessDialog() {
        BERHASIL_DIPERBARUI_DIALOG.pack(); // Pastikan ukuran pas
        BERHASIL_DIPERBARUI_DIALOG.setLocationRelativeTo(this);
        BERHASIL_DIPERBARUI_DIALOG.setVisible(true);
    }
    
    public void showErrorDialog() {
        ERROR_DIALOG.pack();
        ERROR_DIALOG.setLocationRelativeTo(this);
        ERROR_DIALOG.setVisible(true);
    }
    
    public void showDatabaseErrorDialog() {
        DATABASE_ERROR_DIALOG.pack();
        DATABASE_ERROR_DIALOG.setLocationRelativeTo(this);
        DATABASE_ERROR_DIALOG.setVisible(true);
    }
    
    public void showEmptyFieldWarning() {
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.pack();
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setLocationRelativeTo(this);
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setVisible(true);
    }
    // --- BAGIAN GENERATED CODE (Hapus logika di dalamnya) ---
    // Pastikan method ActionPerformed di bawah ini KOSONG di source code Anda
    // Logika sudah dipindah ke Controller via addSimpanListener
    // KOSONGKAN
    // KOSONGKAN


    
         
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BERHASIL_DIPERBARUI_DIALOG = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ERROR_DIALOG = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        DATABASE_ERROR_DIALOG = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MAIN_PANEL = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_PANEL = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_TEXT_PANEL = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_TEXT = new javax.swing.JLabel();
        NAMA_PANEL = new javax.swing.JPanel();
        NAMA_TEXT = new javax.swing.JLabel();
        NAMA_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_PANEL = new javax.swing.JPanel();
        ALAMAT_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_TEXT = new javax.swing.JLabel();
        NO_TELEPON_PANEL = new javax.swing.JPanel();
        NO_TELEPON_TEXT = new javax.swing.JLabel();
        NO_TELEPON_TEXT_FIELD = new javax.swing.JTextField();
        EDIT_BUTTON = new javax.swing.JButton();
        EDIT_BUTTON1 = new javax.swing.JButton();
        ALAMAT_PANEL1 = new javax.swing.JPanel();
        ALAMAT_TEXT1 = new javax.swing.JLabel();
        DAERAH_KIRIMAN_COMBO_BOX = new javax.swing.JComboBox<>();
        MENU_BUTTON = new javax.swing.JButton();

        BERHASIL_DIPERBARUI_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        BERHASIL_DIPERBARUI_DIALOG.setLocationByPlatform(true);
        BERHASIL_DIPERBARUI_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel1.setBackground(new java.awt.Color(205, 228, 223));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Berhasil disimpan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BERHASIL_DIPERBARUI_DIALOGLayout = new javax.swing.GroupLayout(BERHASIL_DIPERBARUI_DIALOG.getContentPane());
        BERHASIL_DIPERBARUI_DIALOG.getContentPane().setLayout(BERHASIL_DIPERBARUI_DIALOGLayout);
        BERHASIL_DIPERBARUI_DIALOGLayout.setHorizontalGroup(
            BERHASIL_DIPERBARUI_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BERHASIL_DIPERBARUI_DIALOGLayout.setVerticalGroup(
            BERHASIL_DIPERBARUI_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ERROR_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        ERROR_DIALOG.setLocationByPlatform(true);
        ERROR_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel2.setBackground(new java.awt.Color(205, 228, 223));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Error");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel16)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ERROR_DIALOGLayout = new javax.swing.GroupLayout(ERROR_DIALOG.getContentPane());
        ERROR_DIALOG.getContentPane().setLayout(ERROR_DIALOGLayout);
        ERROR_DIALOGLayout.setHorizontalGroup(
            ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ERROR_DIALOGLayout.setVerticalGroup(
            ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DATABASE_ERROR_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        DATABASE_ERROR_DIALOG.setLocationByPlatform(true);
        DATABASE_ERROR_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel3.setBackground(new java.awt.Color(205, 228, 223));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Database");

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Error");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout DATABASE_ERROR_DIALOGLayout = new javax.swing.GroupLayout(DATABASE_ERROR_DIALOG.getContentPane());
        DATABASE_ERROR_DIALOG.getContentPane().setLayout(DATABASE_ERROR_DIALOGLayout);
        DATABASE_ERROR_DIALOGLayout.setHorizontalGroup(
            DATABASE_ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DATABASE_ERROR_DIALOGLayout.setVerticalGroup(
            DATABASE_ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setLocationByPlatform(true);
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel4.setBackground(new java.awt.Color(205, 228, 223));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SEMUA KOLOM");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TIDAK BOLEH KOSONG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout = new javax.swing.GroupLayout(SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.getContentPane());
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.getContentPane().setLayout(SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout);
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.setHorizontalGroup(
            SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.setVerticalGroup(
            SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        MAIN_PANEL.setMaximumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setMinimumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setPreferredSize(new java.awt.Dimension(960, 540));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EDIT_DATA_PELANGGAN_PANEL.setBackground(new java.awt.Color(205, 228, 223));
        EDIT_DATA_PELANGGAN_PANEL.setPreferredSize(new java.awt.Dimension(693, 381));

        EDIT_DATA_PELANGGAN_TEXT_PANEL.setBackground(new java.awt.Color(55, 119, 142));

        EDIT_DATA_PELANGGAN_TEXT.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        EDIT_DATA_PELANGGAN_TEXT.setForeground(new java.awt.Color(255, 255, 255));
        EDIT_DATA_PELANGGAN_TEXT.setText("Edit Data Pelanggan");

        javax.swing.GroupLayout EDIT_DATA_PELANGGAN_TEXT_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_PELANGGAN_TEXT_PANEL);
        EDIT_DATA_PELANGGAN_TEXT_PANEL.setLayout(EDIT_DATA_PELANGGAN_TEXT_PANELLayout);
        EDIT_DATA_PELANGGAN_TEXT_PANELLayout.setHorizontalGroup(
            EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_PELANGGAN_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        EDIT_DATA_PELANGGAN_TEXT_PANELLayout.setVerticalGroup(
            EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_PELANGGAN_TEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NAMA_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        NAMA_TEXT.setBackground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setText("Nama:");

        NAMA_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMA_TEXT_FIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NAMA_PANELLayout = new javax.swing.GroupLayout(NAMA_PANEL);
        NAMA_PANEL.setLayout(NAMA_PANELLayout);
        NAMA_PANELLayout.setHorizontalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMA_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NAMA_PANELLayout.setVerticalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_TEXT)
                    .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ALAMAT_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALAMAT_TEXT_FIELDActionPerformed(evt);
            }
        });

        ALAMAT_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT.setText("Alamat");

        javax.swing.GroupLayout ALAMAT_PANELLayout = new javax.swing.GroupLayout(ALAMAT_PANEL);
        ALAMAT_PANEL.setLayout(ALAMAT_PANELLayout);
        ALAMAT_PANELLayout.setHorizontalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(ALAMAT_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANELLayout.setVerticalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALAMAT_TEXT))
                .addContainerGap())
        );

        NO_TELEPON_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        NO_TELEPON_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NO_TELEPON_TEXT.setText("No Telepon");

        NO_TELEPON_TEXT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NO_TELEPON_TEXT_FIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NO_TELEPON_PANELLayout = new javax.swing.GroupLayout(NO_TELEPON_PANEL);
        NO_TELEPON_PANEL.setLayout(NO_TELEPON_PANELLayout);
        NO_TELEPON_PANELLayout.setHorizontalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NO_TELEPON_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NO_TELEPON_PANELLayout.setVerticalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NO_TELEPON_TEXT)
                    .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EDIT_BUTTON.setForeground(new java.awt.Color(65, 82, 154));
        EDIT_BUTTON.setText("Edit");
        EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTONActionPerformed(evt);
            }
        });

        EDIT_BUTTON1.setForeground(new java.awt.Color(65, 82, 154));
        EDIT_BUTTON1.setText("Back");
        EDIT_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTON1ActionPerformed(evt);
            }
        });

        ALAMAT_PANEL1.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT1.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT1.setText("Daerah kiriman");

        DAERAH_KIRIMAN_COMBO_BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DPS-01", "DPS-02", " " }));
        DAERAH_KIRIMAN_COMBO_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAERAH_KIRIMAN_COMBO_BOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ALAMAT_PANEL1Layout = new javax.swing.GroupLayout(ALAMAT_PANEL1);
        ALAMAT_PANEL1.setLayout(ALAMAT_PANEL1Layout);
        ALAMAT_PANEL1Layout.setHorizontalGroup(
            ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DAERAH_KIRIMAN_COMBO_BOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ALAMAT_PANEL1Layout.setVerticalGroup(
            ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALAMAT_PANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DAERAH_KIRIMAN_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALAMAT_TEXT1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EDIT_DATA_PELANGGAN_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_PELANGGAN_PANEL);
        EDIT_DATA_PELANGGAN_PANEL.setLayout(EDIT_DATA_PELANGGAN_PANELLayout);
        EDIT_DATA_PELANGGAN_PANELLayout.setHorizontalGroup(
            EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addComponent(EDIT_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(EDIT_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NAMA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALAMAT_PANEL1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
        EDIT_DATA_PELANGGAN_PANELLayout.setVerticalGroup(
            EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EDIT_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIT_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NAMA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ALAMAT_PANEL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(EDIT_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(EDIT_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
//        DashboardMenu dashboard = new DashboardMenu();
//        dashboard.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    private void NAMA_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMA_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMA_TEXT_FIELDActionPerformed

    private void ALAMAT_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALAMAT_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALAMAT_TEXT_FIELDActionPerformed

    private void NO_TELEPON_TEXT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NO_TELEPON_TEXT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NO_TELEPON_TEXT_FIELDActionPerformed

    private void EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTONActionPerformed

    }//GEN-LAST:event_EDIT_BUTTONActionPerformed

    private void EDIT_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTON1ActionPerformed
//        parentFrame.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_EDIT_BUTTON1ActionPerformed

    private void DAERAH_KIRIMAN_COMBO_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAERAH_KIRIMAN_COMBO_BOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAERAH_KIRIMAN_COMBO_BOXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALAMAT_PANEL;
    private javax.swing.JPanel ALAMAT_PANEL1;
    private javax.swing.JLabel ALAMAT_TEXT;
    private javax.swing.JLabel ALAMAT_TEXT1;
    private javax.swing.JTextField ALAMAT_TEXT_FIELD;
    private javax.swing.JDialog BERHASIL_DIPERBARUI_DIALOG;
    private javax.swing.JComboBox<String> DAERAH_KIRIMAN_COMBO_BOX;
    private javax.swing.JDialog DATABASE_ERROR_DIALOG;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JButton EDIT_BUTTON1;
    private javax.swing.JPanel EDIT_DATA_PELANGGAN_PANEL;
    private javax.swing.JLabel EDIT_DATA_PELANGGAN_TEXT;
    private javax.swing.JPanel EDIT_DATA_PELANGGAN_TEXT_PANEL;
    private javax.swing.JDialog ERROR_DIALOG;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JPanel NAMA_PANEL;
    private javax.swing.JLabel NAMA_TEXT;
    private javax.swing.JTextField NAMA_TEXT_FIELD;
    private javax.swing.JPanel NO_TELEPON_PANEL;
    private javax.swing.JLabel NO_TELEPON_TEXT;
    private javax.swing.JTextField NO_TELEPON_TEXT_FIELD;
    private javax.swing.JDialog SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
