/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.AturJadwalPengiriman;

import java.awt.event.ActionListener;

/**
 *
 * @author Aditya
 */
//Database

public class PilihArmada extends javax.swing.JFrame {

    public PilihArmada() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public String getSelectedArmada() {
        return (String) PILIH_ARMADA_COMBO_BOX.getSelectedItem();
    }
    
    public void addPilihListener(ActionListener listener) {
        jButton1.addActionListener(listener);
    }
    
    public void addMenuListener(ActionListener listener) {
        MENU_BUTTON.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_PANEL = new javax.swing.JPanel();
        PILIH_ARMADA_PANEL = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        PILIH_ARMADA_BOX_PANEL = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PILIH_ARMADA_COMBO_BOX = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        MENU_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PILIH_ARMADA_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        PILIH_ARMADA_PANEL.setMaximumSize(new java.awt.Dimension(960, 540));
        PILIH_ARMADA_PANEL.setMinimumSize(new java.awt.Dimension(960, 540));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PILIH_ARMADA_BOX_PANEL.setBackground(new java.awt.Color(205, 228, 223));

        jPanel4.setBackground(new java.awt.Color(55, 119, 142));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Armada");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PILIH_ARMADA_COMBO_BOX.setBackground(new java.awt.Color(83, 125, 141));
        PILIH_ARMADA_COMBO_BOX.setForeground(new java.awt.Color(255, 255, 255));
        PILIH_ARMADA_COMBO_BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DPS-01", "DPS-02" }));
        PILIH_ARMADA_COMBO_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIH_ARMADA_COMBO_BOXActionPerformed(evt);
            }
        });

        jButton1.setText("Pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PILIH_ARMADA_BOX_PANELLayout = new javax.swing.GroupLayout(PILIH_ARMADA_BOX_PANEL);
        PILIH_ARMADA_BOX_PANEL.setLayout(PILIH_ARMADA_BOX_PANELLayout);
        PILIH_ARMADA_BOX_PANELLayout.setHorizontalGroup(
            PILIH_ARMADA_BOX_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PILIH_ARMADA_BOX_PANELLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
            .addGroup(PILIH_ARMADA_BOX_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PILIH_ARMADA_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PILIH_ARMADA_BOX_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PILIH_ARMADA_BOX_PANELLayout.setVerticalGroup(
            PILIH_ARMADA_BOX_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PILIH_ARMADA_BOX_PANELLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(PILIH_ARMADA_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PILIH_ARMADA_PANELLayout = new javax.swing.GroupLayout(PILIH_ARMADA_PANEL);
        PILIH_ARMADA_PANEL.setLayout(PILIH_ARMADA_PANELLayout);
        PILIH_ARMADA_PANELLayout.setHorizontalGroup(
            PILIH_ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addGroup(PILIH_ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PILIH_ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PILIH_ARMADA_BOX_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(502, 502, 502))
        );
        PILIH_ARMADA_PANELLayout.setVerticalGroup(
            PILIH_ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PILIH_ARMADA_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(PILIH_ARMADA_BOX_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PILIH_ARMADA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PILIH_ARMADA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MAIN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MAIN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PILIH_ARMADA_COMBO_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIH_ARMADA_COMBO_BOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PILIH_ARMADA_COMBO_BOXActionPerformed

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JPanel PILIH_ARMADA_BOX_PANEL;
    private javax.swing.JComboBox<String> PILIH_ARMADA_COMBO_BOX;
    private javax.swing.JPanel PILIH_ARMADA_PANEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
