/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.AturJadwalPengiriman;


import com.mycompany.admin.view.DashboardMenu;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditya
 */

public class UpdateJadwal extends javax.swing.JFrame {

    private int pelangganId;

    public UpdateJadwal(int id, String nama, String alamat, int stok, double harga, int rentang, Date tgl) {
        initComponents();
        this.pelangganId = id;

        // Set Data Awal
        NAMA_PELANGGAN_TEXT.setText(nama);
        ALAMAT_PELANGGAN_TEXT.setText(alamat);
        STOK_GALON_PELANGGAN_TEXT_FIELD.setText(String.valueOf(stok));
        HARGA_PELANGGAN_TEXT_FIELD.setText(String.valueOf(harga));
        RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD.setText(String.valueOf(rentang));
        if (tgl != null) {
            TGL_MULAI_RENTANG_PELANGGAN_DATE.setDate(tgl); // Pastikan nama variabel JDateChooser benar
        }

        this.setLocationRelativeTo(null);
    }

    public int getPelangganId() {
        return pelangganId;
    }

    public String getStokInput() {
        return STOK_GALON_PELANGGAN_TEXT_FIELD.getText();
    }

    public String getHargaInput() {
        return HARGA_PELANGGAN_TEXT_FIELD.getText();
    }

    public String getRentangInput() {
        return RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD.getText();
    }

    public Date getTglInput() {
        return TGL_MULAI_RENTANG_PELANGGAN_DATE.getDate();
    }

    public void addSimpanListener(ActionListener listener) {
        EDIT_BUTTON.addActionListener(listener);
    }

    public void addBackListener(ActionListener listener) {
        BACK_BUTTON.addActionListener(listener);
    }

    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public void showWarning(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    // ... (Hapus logika database di EDIT_BUTTONActionPerformed) ...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_PANEL = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_PANEL = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_TEXT_PANEL = new javax.swing.JPanel();
        EDIT_DATA_PELANGGAN_TEXT = new javax.swing.JLabel();
        NAMA_PANEL = new javax.swing.JPanel();
        NAMA_TEXT = new javax.swing.JLabel();
        NAMA_PELANGGAN_TEXT = new javax.swing.JLabel();
        ALAMAT_PANEL = new javax.swing.JPanel();
        ALAMAT_TEXT = new javax.swing.JLabel();
        ALAMAT_PELANGGAN_TEXT = new javax.swing.JLabel();
        EDIT_BUTTON = new javax.swing.JButton();
        BACK_BUTTON = new javax.swing.JButton();
        ALAMAT_PANEL2 = new javax.swing.JPanel();
        ALAMAT_TEXT2 = new javax.swing.JLabel();
        STOK_GALON_PELANGGAN_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_PANEL3 = new javax.swing.JPanel();
        ALAMAT_TEXT3 = new javax.swing.JLabel();
        HARGA_PELANGGAN_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_PANEL8 = new javax.swing.JPanel();
        ALAMAT_TEXT8 = new javax.swing.JLabel();
        RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD = new javax.swing.JTextField();
        ALAMAT_PANEL9 = new javax.swing.JPanel();
        ALAMAT_TEXT9 = new javax.swing.JLabel();
        TGL_MULAI_RENTANG_PELANGGAN_DATE = new com.toedter.calendar.JDateChooser();
        MENU_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));
        MAIN_PANEL.setMaximumSize(new java.awt.Dimension(960, 540));
        MAIN_PANEL.setMinimumSize(new java.awt.Dimension(960, 540));

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EDIT_DATA_PELANGGAN_PANEL.setBackground(new java.awt.Color(205, 228, 223));
        EDIT_DATA_PELANGGAN_PANEL.setPreferredSize(new java.awt.Dimension(693, 381));

        EDIT_DATA_PELANGGAN_TEXT_PANEL.setBackground(new java.awt.Color(55, 119, 142));

        EDIT_DATA_PELANGGAN_TEXT.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        EDIT_DATA_PELANGGAN_TEXT.setForeground(new java.awt.Color(255, 255, 255));
        EDIT_DATA_PELANGGAN_TEXT.setText("Edit Data Pelanggan");

        javax.swing.GroupLayout EDIT_DATA_PELANGGAN_TEXT_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_PELANGGAN_TEXT_PANEL);
        EDIT_DATA_PELANGGAN_TEXT_PANEL.setLayout(EDIT_DATA_PELANGGAN_TEXT_PANELLayout);
        EDIT_DATA_PELANGGAN_TEXT_PANELLayout.setHorizontalGroup(
            EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_PELANGGAN_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        EDIT_DATA_PELANGGAN_TEXT_PANELLayout.setVerticalGroup(
            EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_PELANGGAN_TEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NAMA_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        NAMA_TEXT.setBackground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setText("Nama:");

        NAMA_PELANGGAN_TEXT.setText("XXXX");

        javax.swing.GroupLayout NAMA_PANELLayout = new javax.swing.GroupLayout(NAMA_PANEL);
        NAMA_PANEL.setLayout(NAMA_PANELLayout);
        NAMA_PANELLayout.setHorizontalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMA_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAMA_PELANGGAN_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NAMA_PANELLayout.setVerticalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_TEXT)
                    .addComponent(NAMA_PELANGGAN_TEXT))
                .addContainerGap())
        );

        ALAMAT_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT.setText("Alamat");

        ALAMAT_PELANGGAN_TEXT.setText("XXXX");

        javax.swing.GroupLayout ALAMAT_PANELLayout = new javax.swing.GroupLayout(ALAMAT_PANEL);
        ALAMAT_PANEL.setLayout(ALAMAT_PANELLayout);
        ALAMAT_PANELLayout.setHorizontalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANELLayout.createSequentialGroup()
                    .addContainerGap(142, Short.MAX_VALUE)
                    .addComponent(ALAMAT_PELANGGAN_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        ALAMAT_PANELLayout.setVerticalGroup(
            ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANELLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(ALAMAT_TEXT)
                .addContainerGap())
            .addGroup(ALAMAT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ALAMAT_PANELLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(ALAMAT_PELANGGAN_TEXT)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        EDIT_BUTTON.setForeground(new java.awt.Color(65, 82, 154));
        EDIT_BUTTON.setText("Simpan");
        EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTONActionPerformed(evt);
            }
        });

        BACK_BUTTON.setForeground(new java.awt.Color(65, 82, 154));
        BACK_BUTTON.setText("Back");
        BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK_BUTTONActionPerformed(evt);
            }
        });

        ALAMAT_PANEL2.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT2.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT2.setText("Stok Galon");

        javax.swing.GroupLayout ALAMAT_PANEL2Layout = new javax.swing.GroupLayout(ALAMAT_PANEL2);
        ALAMAT_PANEL2.setLayout(ALAMAT_PANEL2Layout);
        ALAMAT_PANEL2Layout.setHorizontalGroup(
            ALAMAT_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STOK_GALON_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANEL2Layout.setVerticalGroup(
            ALAMAT_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANEL2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT_TEXT2)
                    .addComponent(STOK_GALON_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ALAMAT_PANEL3.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT3.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT3.setText("Harga");

        javax.swing.GroupLayout ALAMAT_PANEL3Layout = new javax.swing.GroupLayout(ALAMAT_PANEL3);
        ALAMAT_PANEL3.setLayout(ALAMAT_PANEL3Layout);
        ALAMAT_PANEL3Layout.setHorizontalGroup(
            ALAMAT_PANEL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HARGA_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANEL3Layout.setVerticalGroup(
            ALAMAT_PANEL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANEL3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANEL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT_TEXT3)
                    .addComponent(HARGA_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ALAMAT_PANEL8.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT8.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT8.setText("Rentang Pengiriman");

        javax.swing.GroupLayout ALAMAT_PANEL8Layout = new javax.swing.GroupLayout(ALAMAT_PANEL8);
        ALAMAT_PANEL8.setLayout(ALAMAT_PANEL8Layout);
        ALAMAT_PANEL8Layout.setHorizontalGroup(
            ALAMAT_PANEL8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANEL8Layout.setVerticalGroup(
            ALAMAT_PANEL8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANEL8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANEL8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT_TEXT8)
                    .addComponent(RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ALAMAT_PANEL9.setBackground(new java.awt.Color(255, 255, 255));

        ALAMAT_TEXT9.setForeground(new java.awt.Color(65, 82, 154));
        ALAMAT_TEXT9.setText("Tanggal Mulai Rentang");

        TGL_MULAI_RENTANG_PELANGGAN_DATE.setName("TGL_MULAI_RENTANG_PELANGGAN_DATE"); // NOI18N

        javax.swing.GroupLayout ALAMAT_PANEL9Layout = new javax.swing.GroupLayout(ALAMAT_PANEL9);
        ALAMAT_PANEL9.setLayout(ALAMAT_PANEL9Layout);
        ALAMAT_PANEL9Layout.setHorizontalGroup(
            ALAMAT_PANEL9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALAMAT_PANEL9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALAMAT_TEXT9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TGL_MULAI_RENTANG_PELANGGAN_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ALAMAT_PANEL9Layout.setVerticalGroup(
            ALAMAT_PANEL9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALAMAT_PANEL9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ALAMAT_PANEL9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TGL_MULAI_RENTANG_PELANGGAN_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALAMAT_TEXT9))
                .addContainerGap())
        );

        javax.swing.GroupLayout EDIT_DATA_PELANGGAN_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_PELANGGAN_PANEL);
        EDIT_DATA_PELANGGAN_PANEL.setLayout(EDIT_DATA_PELANGGAN_PANELLayout);
        EDIT_DATA_PELANGGAN_PANELLayout.setHorizontalGroup(
            EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addComponent(EDIT_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(BACK_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALAMAT_PANEL2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALAMAT_PANEL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALAMAT_PANEL8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALAMAT_PANEL9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAMA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EDIT_DATA_PELANGGAN_PANELLayout.setVerticalGroup(
            EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createSequentialGroup()
                .addGroup(EDIT_DATA_PELANGGAN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EDIT_DATA_PELANGGAN_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACK_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(NAMA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALAMAT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALAMAT_PANEL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALAMAT_PANEL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALAMAT_PANEL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALAMAT_PANEL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MENU_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BUTTON.setPreferredSize(new java.awt.Dimension(72, 72));
        MENU_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(EDIT_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 51, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addComponent(MENU_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EDIT_DATA_PELANGGAN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTONActionPerformed

    }//GEN-LAST:event_EDIT_BUTTONActionPerformed

    private void BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK_BUTTONActionPerformed

    }//GEN-LAST:event_BACK_BUTTONActionPerformed

    private void MENU_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BUTTONActionPerformed
        DashboardMenu dashboard = new DashboardMenu();
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MENU_BUTTONActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALAMAT_PANEL;
    private javax.swing.JPanel ALAMAT_PANEL2;
    private javax.swing.JPanel ALAMAT_PANEL3;
    private javax.swing.JPanel ALAMAT_PANEL8;
    private javax.swing.JPanel ALAMAT_PANEL9;
    private javax.swing.JLabel ALAMAT_PELANGGAN_TEXT;
    private javax.swing.JLabel ALAMAT_TEXT;
    private javax.swing.JLabel ALAMAT_TEXT2;
    private javax.swing.JLabel ALAMAT_TEXT3;
    private javax.swing.JLabel ALAMAT_TEXT8;
    private javax.swing.JLabel ALAMAT_TEXT9;
    private javax.swing.JButton BACK_BUTTON;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JPanel EDIT_DATA_PELANGGAN_PANEL;
    private javax.swing.JLabel EDIT_DATA_PELANGGAN_TEXT;
    private javax.swing.JPanel EDIT_DATA_PELANGGAN_TEXT_PANEL;
    private javax.swing.JTextField HARGA_PELANGGAN_TEXT_FIELD;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BUTTON;
    private javax.swing.JPanel NAMA_PANEL;
    private javax.swing.JLabel NAMA_PELANGGAN_TEXT;
    private javax.swing.JLabel NAMA_TEXT;
    private javax.swing.JTextField RENTANG_PENGIRIMAN_PELANGGAN_TEXT_FIELD;
    private javax.swing.JTextField STOK_GALON_PELANGGAN_TEXT_FIELD;
    private com.toedter.calendar.JDateChooser TGL_MULAI_RENTANG_PELANGGAN_DATE;
    // End of variables declaration//GEN-END:variables
}
