/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin.view.kelola_data_sopir;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class EditDataSopir extends javax.swing.JFrame {

    // Constructor sederhana untuk inisialisasi komponen
    public EditDataSopir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    // Method untuk mengisi form saat pertama kali dibuka (Dipanggil Controller)
    public void setFormData(String nama, String noHp, String armada, String username, String password) {
        NAMA_TEXT_FIELD.setText(nama);
        NO_TELEPON_TEXT_FIELD.setText(noHp);
        PILIH_ARMADA_COMBO_BOX.setSelectedItem(armada);
        USERNAME_TEXT_FIELD.setText(username);
        PASSWORD_TEXT_FIELD.setText(password);
    }

    // Getters
    public String getNama() { return NAMA_TEXT_FIELD.getText(); }
    public String getNoTelepon() { return NO_TELEPON_TEXT_FIELD.getText(); }
    public String getUsername() { return USERNAME_TEXT_FIELD.getText(); }
    public String getPassword() { return PASSWORD_TEXT_FIELD.getText(); } // Perhatikan jika pakai JPasswordField harus new String(getPassword())
    public String getArmada() { return (String) PILIH_ARMADA_COMBO_BOX.getSelectedItem(); }

    public void addUpdateListener(ActionListener listener) {
        EDIT_BUTTON.addActionListener(listener);
    }
    
    public void addMenuListener(ActionListener listener) {
        MENU_BOTTON.addActionListener(listener);
    }
    
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    // ... (initComponents tetap sama)


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BERHASIL_DIPERBARUI_DIALOG = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ERROR_DIALOG = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        DATABASE_ERROR_DIALOG = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MAIN_PANEL = new javax.swing.JPanel();
        MENU_BOTTON = new javax.swing.JButton();
        EDIT_DATA_SOPIR_PANEL = new javax.swing.JPanel();
        EDIT_DATA_SOPIR_TEXT_PANEL = new javax.swing.JPanel();
        EDIT_DATA_SOPIR_TEXT = new javax.swing.JLabel();
        NAMA_PANEL = new javax.swing.JPanel();
        NAMA_TEXT = new javax.swing.JLabel();
        NAMA_TEXT_FIELD = new javax.swing.JTextField();
        NO_TELEPON_PANEL = new javax.swing.JPanel();
        NO_TELEPON_TEXT = new javax.swing.JLabel();
        NO_TELEPON_TEXT_FIELD = new javax.swing.JTextField();
        USERNAME_PANEL = new javax.swing.JPanel();
        USERNAME_TEXT = new javax.swing.JLabel();
        USERNAME_TEXT_FIELD = new javax.swing.JTextField();
        PASSWORD_PANEL = new javax.swing.JPanel();
        PASSWORD_TEXT = new javax.swing.JLabel();
        PASSWORD_TEXT_FIELD = new javax.swing.JTextField();
        ARMADA_PANEL = new javax.swing.JPanel();
        ARMADA_TEXT = new javax.swing.JLabel();
        PILIH_ARMADA_COMBO_BOX = new javax.swing.JComboBox<>();
        EDIT_BUTTON = new javax.swing.JButton();
        HeaderD = new javax.swing.JPanel();
        HeaderU = new javax.swing.JPanel();
        HeaderD1 = new javax.swing.JPanel();
        HeaderU1 = new javax.swing.JPanel();

        BERHASIL_DIPERBARUI_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        BERHASIL_DIPERBARUI_DIALOG.setLocationByPlatform(true);
        BERHASIL_DIPERBARUI_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel1.setBackground(new java.awt.Color(205, 228, 223));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEMUA KOLOM");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TIDAK BOLEH KOSONG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout BERHASIL_DIPERBARUI_DIALOGLayout = new javax.swing.GroupLayout(BERHASIL_DIPERBARUI_DIALOG.getContentPane());
        BERHASIL_DIPERBARUI_DIALOG.getContentPane().setLayout(BERHASIL_DIPERBARUI_DIALOGLayout);
        BERHASIL_DIPERBARUI_DIALOGLayout.setHorizontalGroup(
            BERHASIL_DIPERBARUI_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BERHASIL_DIPERBARUI_DIALOGLayout.setVerticalGroup(
            BERHASIL_DIPERBARUI_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ERROR_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        ERROR_DIALOG.setLocationByPlatform(true);
        ERROR_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel2.setBackground(new java.awt.Color(205, 228, 223));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Error");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel16)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ERROR_DIALOGLayout = new javax.swing.GroupLayout(ERROR_DIALOG.getContentPane());
        ERROR_DIALOG.getContentPane().setLayout(ERROR_DIALOGLayout);
        ERROR_DIALOGLayout.setHorizontalGroup(
            ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ERROR_DIALOGLayout.setVerticalGroup(
            ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DATABASE_ERROR_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        DATABASE_ERROR_DIALOG.setLocationByPlatform(true);
        DATABASE_ERROR_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel3.setBackground(new java.awt.Color(205, 228, 223));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Database");

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Error");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout DATABASE_ERROR_DIALOGLayout = new javax.swing.GroupLayout(DATABASE_ERROR_DIALOG.getContentPane());
        DATABASE_ERROR_DIALOG.getContentPane().setLayout(DATABASE_ERROR_DIALOGLayout);
        DATABASE_ERROR_DIALOGLayout.setHorizontalGroup(
            DATABASE_ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DATABASE_ERROR_DIALOGLayout.setVerticalGroup(
            DATABASE_ERROR_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setBackground(new java.awt.Color(205, 228, 223));
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setLocationByPlatform(true);
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.setSize(new java.awt.Dimension(200, 164));

        jPanel4.setBackground(new java.awt.Color(205, 228, 223));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SEMUA KOLOM");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TIDAK BOLEH KOSONG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout = new javax.swing.GroupLayout(SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.getContentPane());
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG.getContentPane().setLayout(SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout);
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.setHorizontalGroup(
            SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.setVerticalGroup(
            SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        MAIN_PANEL.setBackground(new java.awt.Color(172, 210, 202));

        MENU_BOTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/Menu_Dark.png"))); // NOI18N
        MENU_BOTTON.setPreferredSize(new java.awt.Dimension(55, 55));
        MENU_BOTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_BOTTONActionPerformed(evt);
            }
        });

        EDIT_DATA_SOPIR_PANEL.setBackground(new java.awt.Color(220, 238, 235));

        EDIT_DATA_SOPIR_TEXT_PANEL.setBackground(new java.awt.Color(55, 119, 142));

        EDIT_DATA_SOPIR_TEXT.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        EDIT_DATA_SOPIR_TEXT.setForeground(new java.awt.Color(255, 255, 255));
        EDIT_DATA_SOPIR_TEXT.setText("Edit Data Sopir");

        javax.swing.GroupLayout EDIT_DATA_SOPIR_TEXT_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_SOPIR_TEXT_PANEL);
        EDIT_DATA_SOPIR_TEXT_PANEL.setLayout(EDIT_DATA_SOPIR_TEXT_PANELLayout);
        EDIT_DATA_SOPIR_TEXT_PANELLayout.setHorizontalGroup(
            EDIT_DATA_SOPIR_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_SOPIR_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_SOPIR_TEXT)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        EDIT_DATA_SOPIR_TEXT_PANELLayout.setVerticalGroup(
            EDIT_DATA_SOPIR_TEXT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_SOPIR_TEXT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDIT_DATA_SOPIR_TEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NAMA_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NAMA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NAMA_TEXT.setText("Nama :");

        javax.swing.GroupLayout NAMA_PANELLayout = new javax.swing.GroupLayout(NAMA_PANEL);
        NAMA_PANEL.setLayout(NAMA_PANELLayout);
        NAMA_PANELLayout.setHorizontalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMA_TEXT)
                .addGap(41, 41, 41)
                .addComponent(NAMA_TEXT_FIELD)
                .addContainerGap())
        );
        NAMA_PANELLayout.setVerticalGroup(
            NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMA_PANELLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(NAMA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_TEXT)
                    .addComponent(NAMA_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NO_TELEPON_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NO_TELEPON_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        NO_TELEPON_TEXT.setText("No Telepon :");

        javax.swing.GroupLayout NO_TELEPON_PANELLayout = new javax.swing.GroupLayout(NO_TELEPON_PANEL);
        NO_TELEPON_PANEL.setLayout(NO_TELEPON_PANELLayout);
        NO_TELEPON_PANELLayout.setHorizontalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NO_TELEPON_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NO_TELEPON_TEXT_FIELD)
                .addContainerGap())
        );
        NO_TELEPON_PANELLayout.setVerticalGroup(
            NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NO_TELEPON_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NO_TELEPON_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NO_TELEPON_TEXT)
                    .addComponent(NO_TELEPON_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        USERNAME_TEXT.setBackground(new java.awt.Color(65, 82, 154));
        USERNAME_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        USERNAME_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        USERNAME_TEXT.setText("Username :");

        javax.swing.GroupLayout USERNAME_PANELLayout = new javax.swing.GroupLayout(USERNAME_PANEL);
        USERNAME_PANEL.setLayout(USERNAME_PANELLayout);
        USERNAME_PANELLayout.setHorizontalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USERNAME_TEXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(USERNAME_TEXT_FIELD)
                .addContainerGap())
        );
        USERNAME_PANELLayout.setVerticalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USERNAME_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_TEXT)
                    .addComponent(USERNAME_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        PASSWORD_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PASSWORD_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        PASSWORD_TEXT.setText("Password :");

        javax.swing.GroupLayout PASSWORD_PANELLayout = new javax.swing.GroupLayout(PASSWORD_PANEL);
        PASSWORD_PANEL.setLayout(PASSWORD_PANELLayout);
        PASSWORD_PANELLayout.setHorizontalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PASSWORD_TEXT)
                .addGap(18, 18, 18)
                .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        PASSWORD_PANELLayout.setVerticalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PASSWORD_PANELLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD_TEXT)
                    .addComponent(PASSWORD_TEXT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ARMADA_TEXT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ARMADA_TEXT.setForeground(new java.awt.Color(65, 82, 154));
        ARMADA_TEXT.setText("Armada :");

        PILIH_ARMADA_COMBO_BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DPS-01", "DPS-02" }));
        PILIH_ARMADA_COMBO_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIH_ARMADA_COMBO_BOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARMADA_PANELLayout = new javax.swing.GroupLayout(ARMADA_PANEL);
        ARMADA_PANEL.setLayout(ARMADA_PANELLayout);
        ARMADA_PANELLayout.setHorizontalGroup(
            ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ARMADA_TEXT)
                .addGap(30, 30, 30)
                .addComponent(PILIH_ARMADA_COMBO_BOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ARMADA_PANELLayout.setVerticalGroup(
            ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARMADA_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ARMADA_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ARMADA_TEXT)
                    .addComponent(PILIH_ARMADA_COMBO_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        EDIT_BUTTON.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EDIT_BUTTON.setForeground(new java.awt.Color(65, 82, 154));
        EDIT_BUTTON.setText("Edit");
        EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EDIT_DATA_SOPIR_PANELLayout = new javax.swing.GroupLayout(EDIT_DATA_SOPIR_PANEL);
        EDIT_DATA_SOPIR_PANEL.setLayout(EDIT_DATA_SOPIR_PANELLayout);
        EDIT_DATA_SOPIR_PANELLayout.setHorizontalGroup(
            EDIT_DATA_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_SOPIR_PANELLayout.createSequentialGroup()
                .addComponent(EDIT_DATA_SOPIR_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
            .addGroup(EDIT_DATA_SOPIR_PANELLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(EDIT_DATA_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EDIT_BUTTON)
                    .addGroup(EDIT_DATA_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PASSWORD_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(USERNAME_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NAMA_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ARMADA_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EDIT_DATA_SOPIR_PANELLayout.setVerticalGroup(
            EDIT_DATA_SOPIR_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDIT_DATA_SOPIR_PANELLayout.createSequentialGroup()
                .addComponent(EDIT_DATA_SOPIR_TEXT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAMA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NO_TELEPON_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(USERNAME_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PASSWORD_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ARMADA_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDIT_BUTTON)
                .addGap(28, 28, 28))
        );

        HeaderD.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderULayout = new javax.swing.GroupLayout(HeaderU);
        HeaderU.setLayout(HeaderULayout);
        HeaderULayout.setHorizontalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderULayout.setVerticalGroup(
            HeaderULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addComponent(HeaderU, 25, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        HeaderD1.setBackground(new java.awt.Color(44, 97, 116));
        HeaderD1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderD1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderD1.setPreferredSize(new java.awt.Dimension(375, 52));

        HeaderU1.setBackground(new java.awt.Color(46, 86, 103));
        HeaderU1.setMaximumSize(new java.awt.Dimension(1920, 26));
        HeaderU1.setMinimumSize(new java.awt.Dimension(1920, 0));
        HeaderU1.setPreferredSize(new java.awt.Dimension(375, 26));

        javax.swing.GroupLayout HeaderU1Layout = new javax.swing.GroupLayout(HeaderU1);
        HeaderU1.setLayout(HeaderU1Layout);
        HeaderU1Layout.setHorizontalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        HeaderU1Layout.setVerticalGroup(
            HeaderU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderD1Layout = new javax.swing.GroupLayout(HeaderD1);
        HeaderD1.setLayout(HeaderD1Layout);
        HeaderD1Layout.setHorizontalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderD1Layout.setVerticalGroup(
            HeaderD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderD1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(HeaderU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MAIN_PANELLayout = new javax.swing.GroupLayout(MAIN_PANEL);
        MAIN_PANEL.setLayout(MAIN_PANELLayout);
        MAIN_PANELLayout.setHorizontalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENU_BOTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(EDIT_DATA_SOPIR_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
            .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
        );
        MAIN_PANELLayout.setVerticalGroup(
            MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELLayout.createSequentialGroup()
                .addComponent(HeaderD, 49, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MAIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MENU_BOTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MAIN_PANELLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(EDIT_DATA_SOPIR_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(HeaderD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_PANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_BOTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_BOTTONActionPerformed

    }//GEN-LAST:event_MENU_BOTTONActionPerformed

    private void EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTONActionPerformed

    }//GEN-LAST:event_EDIT_BUTTONActionPerformed

    private void PILIH_ARMADA_COMBO_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIH_ARMADA_COMBO_BOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PILIH_ARMADA_COMBO_BOXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ARMADA_PANEL;
    private javax.swing.JLabel ARMADA_TEXT;
    private javax.swing.JDialog BERHASIL_DIPERBARUI_DIALOG;
    private javax.swing.JDialog DATABASE_ERROR_DIALOG;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JPanel EDIT_DATA_SOPIR_PANEL;
    private javax.swing.JLabel EDIT_DATA_SOPIR_TEXT;
    private javax.swing.JPanel EDIT_DATA_SOPIR_TEXT_PANEL;
    private javax.swing.JDialog ERROR_DIALOG;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderD1;
    private javax.swing.JPanel HeaderU;
    private javax.swing.JPanel HeaderU1;
    private javax.swing.JPanel MAIN_PANEL;
    private javax.swing.JButton MENU_BOTTON;
    private javax.swing.JPanel NAMA_PANEL;
    private javax.swing.JLabel NAMA_TEXT;
    private javax.swing.JTextField NAMA_TEXT_FIELD;
    private javax.swing.JPanel NO_TELEPON_PANEL;
    private javax.swing.JLabel NO_TELEPON_TEXT;
    private javax.swing.JTextField NO_TELEPON_TEXT_FIELD;
    private javax.swing.JPanel PASSWORD_PANEL;
    private javax.swing.JLabel PASSWORD_TEXT;
    private javax.swing.JTextField PASSWORD_TEXT_FIELD;
    private javax.swing.JComboBox<String> PILIH_ARMADA_COMBO_BOX;
    private javax.swing.JDialog SEMUA_KOLOM_TIDAK_BOLEH_KOSONG_DIALOG;
    private javax.swing.JPanel USERNAME_PANEL;
    private javax.swing.JLabel USERNAME_TEXT;
    private javax.swing.JTextField USERNAME_TEXT_FIELD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
